analytics: {}
color:
  brandColors:
    - '#A0C0C0'
    - '#2A455A'
    - '#5088A0'
    - '#406888'
    - '#000000'
  brandStrength: 0.894014
  lightness: 0.050203
  rhythmicContrast: 0.238769
  saturation: 0.608324
cta: {}
layout_spectrum: 0.409909
name: festival hobos
opengraph: {}
purpose: {}
typography_spectrum: 0.598309
